//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libCodiceFiscale.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuni
    {
        public int ID { get; set; }
        public string Codice { get; set; }
        public string Provincia { get; set; }
        public string Comune { get; set; }
    }
}
